name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv pip install --system -r requirements.txt
        
    - name: Run linter
      run: make lint
      
    - name: Start Database
      run: |
        docker compose up -d db
        echo "Waiting for postgres..."
        until docker compose exec db pg_isready -U postgres; do sleep 1; done
        
    - name: Run Database Migrations
      env:
        DATABASE_URL: postgresql://postgres@127.0.0.1:5433/postgres
      run: |
        make migrate
        alembic check
      
    - name: Run tests
      run: make test
